_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://pyebwa-auth:9999
    routes:
      - name: auth-v1-all
        paths:
          - /auth/v1/
        strip_path: true

  - name: rest-v1
    url: http://pyebwa-rest:3000
    routes:
      - name: rest-v1-all
        paths:
          - /rest/v1/
        strip_path: true

  - name: realtime-v1
    url: http://pyebwa-realtime:4000
    routes:
      - name: realtime-v1-all
        paths:
          - /realtime/v1/
        strip_path: true

  - name: storage-v1
    url: http://pyebwa-storage:5000
    routes:
      - name: storage-v1-all
        paths:
          - /storage/v1/
        strip_path: true

  - name: meta-v1
    url: http://pyebwa-meta:8080
    routes:
      - name: meta-v1-all
        paths:
          - /pg/
        strip_path: true

  - name: imgproxy-v1
    url: http://pyebwa-imgproxy:5001
    routes:
      - name: imgproxy-v1-all
        paths:
          - /imgproxy/
        strip_path: true

  - name: studio
    url: http://pyebwa-studio:3000
    routes:
      - name: studio-all
        paths:
          - /
