// Translation system for Pyebwa app
const translations = {
    en: {
        // Navigation
        navDashboard: "Dashboard",
        navTree: "Family Tree",
        navMembers: "Members",
        navStories: "Stories",
        
        // User menu
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        
        // Common
        loading: "Loading...",
        search: "Search...",
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        export: "Export",
        
        // Family tree
        familyTree: "My Family Tree",
        addMember: "Add Member",
        addFamilyMember: "Add Family Member",
        
        // Member fields
        firstName: "First Name",
        lastName: "Last Name",
        gender: "Gender",
        male: "Male",
        female: "Female",
        birthDate: "Birth Date",
        deathDate: "Death Date",
        biography: "Biography",
        photo: "Photo",
        email: "Email",
        
        // Relationships
        relationship: "Relationship",
        selectRelationship: "Select relationship",
        relatedTo: "Related to",
        parent: "Parent",
        child: "Child",
        spouse: "Spouse",
        sibling: "Sibling",
        
        // Members view
        familyMembers: "Family Members",
        memberCount: "{count} members",
        
        // Stories
        familyStories: "Family Stories",
        addStory: "Add Story",
        storyTitle: "Title",
        storyContent: "Story",
        storyDate: "Date",
        noStoriesYet: "No stories yet",
        startSharing: "Start sharing your family stories and memories.",
        comingSoon: "Stories feature coming soon!",
        
        // Messages
        welcomeBack: "Welcome back",
        noMembersYet: "No family members added yet.",
        startBuilding: "Start building your family tree by adding your first member.",
        confirmDelete: "Are you sure you want to delete {name}?",
        savedSuccessfully: "Saved successfully!",
        errorSaving: "Error saving. Please try again.",
        deletedSuccessfully: "Deleted successfully!",
        errorDeleting: "Error deleting member",
        update: "Update",
        editFamilyMember: "Edit Family Member",
        selectPerson: "Select person",
        updatedSuccessfully: "Updated successfully!",
        
        // Dashboard
        familyTreeSummary: "Your family tree has",
        members: "members",
        acrossGenerations: "across",
        generations: "generations",
        totalMembers: "Total Members",
        males: "Males",
        females: "Females",
        quickActions: "Quick Actions",
        viewTree: "View Tree",
        browsemembers: "Browse Members",
        exportTree: "Export Tree",
        recentActivity: "Recent Activity",
        familyInsights: "Family Insights",
        averageAge: "Average Age",
        years: "years",
        youngestMember: "Youngest Member",
        oldestMember: "Oldest Member",
        photosUploaded: "Photos Uploaded",
        memberAdded: "New member added",
        photoUploaded: "Photo uploaded",
        profileUpdated: "Profile updated",
        today: "Today",
        yesterday: "Yesterday",
        daysAgo: "{{days}} days ago",
        treeExported: "Family tree exported successfully!",
        yearsOld: "years old",
        
        // PDF Export
        exportFamilyTree: "Export Family Tree",
        exportAsPDF: "Export as PDF",
        exportAsJSON: "Export as JSON",
        pdfDescription: "Visual family tree with charts and demographic statistics",
        jsonDescription: "Raw data format for backup or data analysis",
        recommended: "Recommended",
        pdfExported: "Family tree exported as PDF successfully!",
        jsonExported: "Family tree data exported successfully!",
        pdfExportError: "Error generating PDF. Please try again.",
        pdfExportNotAvailable: "PDF export is loading, please try again.",
        generatingPDF: "Generating PDF...",
        pleaseWait: "Please wait while we create your family tree report",
        familyTreeReport: "Family Tree Report",
        familyStatistics: "Family Statistics",
        genderDistribution: "Gender Distribution",
        ageDistribution: "Age Distribution",
        numberOfMembers: "Number of Members",
        generationBreakdown: "Generation Breakdown",
        currentGeneration: "Current Generation",
        parentsGeneration: "Parents Generation",
        grandparentsGeneration: "Grandparents Generation",
        greatGrandparentsGeneration: "Great-Grandparents Generation",
        generation: "Generation",
        generatedBy: "Generated by",
        yourFamilyTree: "Your Family Tree",
        
        // Onboarding
        welcomeToPyebwa: "Welcome to Pyebwa",
        onboardingWelcomeText: "Build and preserve your family tree with our beautiful, easy-to-use platform.",
        visualFamilyTree: "Visual Family Tree",
        visualTreeDesc: "See your family connections in a beautiful tree view",
        photoMemories: "Photo Memories",
        photoMemoriesDesc: "Add photos to preserve precious memories",
        familyStories: "Family Stories",
        familyStoriesDesc: "Document and share family stories for generations",
        letsGetStarted: "Let's Get Started",
        addFirstMemberPrompt: "Add your first family member to begin building your tree.",
        skip: "Skip",
        next: "Next",
        getStarted: "Get Started",
        welcomeMessage: "Welcome to your family tree!",
        
        // Footer
        poweredBy: "Powered by",
    },
    
    fr: {
        // Navigation
        navDashboard: "Tableau de bord",
        navTree: "Arbre Généalogique",
        navMembers: "Membres",
        navStories: "Histoires",
        
        // User menu
        profile: "Profil",
        settings: "Paramètres",
        logout: "Déconnexion",
        
        // Common
        loading: "Chargement...",
        search: "Rechercher...",
        save: "Enregistrer",
        cancel: "Annuler",
        delete: "Supprimer",
        edit: "Modifier",
        view: "Voir",
        
        // Family tree
        familyTree: "Mon Arbre Généalogique",
        addMember: "Ajouter Membre",
        addFamilyMember: "Ajouter un Membre de la Famille",
        
        // Member fields
        firstName: "Prénom",
        lastName: "Nom",
        gender: "Sexe",
        male: "Homme",
        female: "Femme",
        birthDate: "Date de Naissance",
        deathDate: "Date de Décès",
        biography: "Biographie",
        photo: "Photo",
        email: "Email",
        
        // Relationships
        relationship: "Relation",
        selectRelationship: "Sélectionner la relation",
        relatedTo: "Lié à",
        parent: "Parent",
        child: "Enfant",
        spouse: "Conjoint(e)",
        sibling: "Frère/Sœur",
        
        // Members view
        familyMembers: "Membres de la Famille",
        memberCount: "{count} membres",
        
        // Stories
        familyStories: "Histoires Familiales",
        addStory: "Ajouter Histoire",
        storyTitle: "Titre",
        storyContent: "Histoire",
        storyDate: "Date",
        noStoriesYet: "Aucune histoire pour le moment",
        startSharing: "Commencez à partager vos histoires et souvenirs familiaux.",
        comingSoon: "La fonction histoires arrive bientôt!",
        
        // Messages
        welcomeBack: "Bon retour",
        noMembersYet: "Aucun membre de famille ajouté.",
        startBuilding: "Commencez à construire votre arbre en ajoutant votre premier membre.",
        confirmDelete: "Êtes-vous sûr de vouloir supprimer {name}?",
        savedSuccessfully: "Enregistré avec succès!",
        errorSaving: "Erreur lors de l'enregistrement. Veuillez réessayer.",
        deletedSuccessfully: "Supprimé avec succès!",
        errorDeleting: "Erreur lors de la suppression",
        update: "Mettre à jour",
        editFamilyMember: "Modifier Membre de la Famille",
        selectPerson: "Sélectionner une personne",
        updatedSuccessfully: "Mis à jour avec succès!",
        
        // Footer
        poweredBy: "Propulsé par",
    },
    
    ht: {
        // Navigation
        navDashboard: "Tablo",
        navTree: "Pyebwa Fanmi",
        navMembers: "Manm yo",
        navStories: "Istwa",
        
        // User menu
        profile: "Pwofil",
        settings: "Paramèt",
        logout: "Dekonekte",
        
        // Common
        loading: "Chajman...",
        search: "Chèche...",
        save: "Anrejistre",
        cancel: "Anile",
        delete: "Efase",
        edit: "Modifye",
        view: "Gade",
        
        // Family tree
        familyTree: "Pyebwa Fanmi Mwen",
        addMember: "Ajoute Manm",
        addFamilyMember: "Ajoute Manm Fanmi",
        
        // Member fields
        firstName: "Non",
        lastName: "Siyati",
        gender: "Sèks",
        male: "Gason",
        female: "Fi",
        birthDate: "Dat nesans",
        deathDate: "Dat lanmò",
        biography: "Biyografi",
        photo: "Foto",
        email: "Imèl",
        
        // Relationships
        relationship: "Relasyon",
        selectRelationship: "Chwazi relasyon",
        relatedTo: "An relasyon ak",
        parent: "Paran",
        child: "Pitit",
        spouse: "Mari/Madanm",
        sibling: "Frè/Sè",
        
        // Members view
        familyMembers: "Manm Fanmi yo",
        memberCount: "{count} manm",
        
        // Stories
        familyStories: "Istwa Fanmi",
        addStory: "Ajoute Istwa",
        storyTitle: "Tit",
        storyContent: "Istwa",
        storyDate: "Dat",
        noStoriesYet: "Poko gen istwa",
        startSharing: "Kòmanse pataje istwa ak souvni fanmi ou yo.",
        comingSoon: "Fonksyon istwa ap vini byento!",
        
        // Messages
        welcomeBack: "Byenveni ankò",
        noMembersYet: "Poko gen manm fanmi ki ajoute.",
        startBuilding: "Kòmanse bati pyebwa w nan ajoute premye manm lan.",
        confirmDelete: "Ou sèten ou vle efase {name}?",
        savedSuccessfully: "Anrejistre avèk siksè!",
        errorSaving: "Erè pandan anrejistreman. Tanpri eseye ankò.",
        deletedSuccessfully: "Efase avèk siksè!",
        errorDeleting: "Erè pandan efasman",
        update: "Mete ajou",
        editFamilyMember: "Modifye Manm Fanmi",
        selectPerson: "Chwazi yon moun",
        updatedSuccessfully: "Mete ajou avèk siksè!",
        
        // Footer
        poweredBy: "Powered by",
    }
};

// Current language (default to Haitian Creole)
// Check cookie first for cross-domain persistence
let currentLanguage = window.getUserPreference ? window.getUserPreference('lang', 'ht') : (localStorage.getItem('pyebwaLang') || 'ht');

// Translation function
window.t = function(key, params = {}) {
    let text = translations[currentLanguage][key] || translations['en'][key] || key;
    
    // Replace parameters like {count} with actual values
    Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param]);
    });
    
    return text;
}

// Update all elements with data-i18n attribute
window.updateTranslations = function() {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        element.textContent = t(key);
    });
    
    // Update placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
        const key = element.getAttribute('data-i18n-placeholder');
        element.placeholder = t(key);
    });
}

// Change language
window.setLanguage = function(lang) {
    currentLanguage = lang;
    // Store in both cookie and localStorage
    if (window.storeUserPreference) {
        window.storeUserPreference('lang', lang);
    } else {
        localStorage.setItem('pyebwaLang', lang);
    }
    updateTranslations();
    
    // Update active language button
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });
}