name: Security Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
    
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
    
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: javascript, python
    
    - name: Check for hardcoded credentials
      run: |
        # Check for potential API keys, passwords, etc.
        ! grep -r -E "(api[_-]?key|password|secret|token)\s*[:=]\s*['\"][^'\"]+['\"]" \
          --include="*.js" --include="*.py" --include="*.html" \
          --exclude-dir=node_modules --exclude-dir=.git \
          . || echo "Warning: Potential hardcoded credentials found"